[Graphics]
; 1 - OpenGL 3.3
; 2 - OpenGL 4.5
; 3 - Vulkan
; 4 - Direct3D 11
; 5 - Direct3D 12
; 6 - Metal
; 7 - NVN
; 8 - GNM
RenderingBackend=1


[Window]
Width=1280
Height=720
;le parser de hge n'accepte pas les espaces
Title="MyGame"
;fermer immédiatement le jeu lorsque l'utilisateur appuie sur la croix de la fenêtre
QuitOnClose=1